source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem 'audited', '~> 4.5'
gem 'cancancan'
gem 'enumerize'
gem 'kaminari'
gem 'knock'
gem 'pg'
gem 'puma', '~> 3.7'
gem 'rack-cors', require: 'rack/cors'
gem 'rails', '~> 5.1.4'

group :development, :test do
  gem 'bullet'
  gem 'rspec-rails', '~> 3.7'
  gem 'rswag-specs'
end

group :development do
  gem 'better_errors'
  gem 'rubocop', require: false
  gem 'rubocop-rspec', require: false
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
